### PR TITLE
Loosen Capybara dependency for Capybara (both 2.4+ and 3)

### PR DESCRIPTION
**Pull request by jesperronn**
This fixes https://github.com/gonzalo-bulnes/dredd-rack/issues/43

### CODE REVIEW

**Comment by jesperronn** [comment]
I would really like this change to go in and be released. @gonzalo-bulnes if you approve and merge, would you publish new version, please?

**Comment by gonzalo-bulnes** [comment]
Hey @jesperronn, could you please rebase your branch onto the latest `master`? I'm getting a feeling that if I do I'll end up a copy of the changes.

It is not a huge deal for me, but I think it's nicer to merge _your_ branch...

**Comment by gonzalo-bulnes** [comment]
In terms of the release, I think I'll jump on the opportunity to go to *v1.0.0*.

I'm not experimenting much these days, and it seems that it would be useful to commit to the interfaces that are in place. Any thoughts?

**Comment by jesperronn** [comment]
> In terms of the release, I think I'll jump on the opportunity to go to **v1.0.0**.

Awesome! Jump to major is the obvious choice, now that code is pretty stable. Thanks!

**Comment by pilgunboris** [comment]
Please release the new version of the gem to be able to upgrade the Capybara.

**Comment by gonzalo-bulnes** [comment]
Hi @jesperronn, just in case you're wondering, I cherry-picked your commits in #46. It's not you it's me, I've a thing for linear git logs and I rebased your branch instead of merging `master` back in. :wink: 

Thank you for your PR, your contribution is now available in [**v1.0.0**](https://github.com/gonzalo-bulnes/dredd-rack/releases/tag/v1.0.0)! :clap:

**Pull request closed without merging**
