### PR TITLE
Testing the gem on multiple ruby versions (Travis)

### PR DESCRIPTION
**Pull request by jesperronn**
I updated to latest known version for each ruby including the outdated v2.2 that was already here.

Later I suggest updating the dependencies and remove the unsupported rubies.

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
Hi @jesperronn!

Thank you for you PR! I can only agree that removing the unsupported versions of Ruby from the test suite makes sense, you make a very good point :+1: 

Regarding which ones to add, I would prefer not adding too many Ruby versions here, but pick the most relevant instead.

**Why?**

Each of them will cause Travis CI to run a separate build, which is fine (and what we want) from a testing perspective.

Yet, considering that it is _very_ unlikely that any of this code is really going to break for one Ruby version and not another (this code deosn't do anything really fancy) I would rather not spend too many cycles in running builds that are very unlikely to teach us anything new, for tow reasons:

- Travis CI is supporting the open source community, which I am really grateful for and I'd like to believe we're being considerate with their investment
- also I'd like rather not heating the planet running more builds than useful?

Does this make sense to you? What versions of Ruby do you think are most interesting to test against?

**Comment by jesperronn** [comment]
@gonzalo-bulnes You have a good point, and let's go with the argument to not load Travis with too much work. Should we go with the oldest supported ruby (currently 2.4) or the latest 2.6?

The users would at least want to be able to choose ruby version without this gem dictating which version is required. And I think you are already there.

This also means to restrain from using new constructs in code from recent rubies, (example Ruby2.6#filter or Ruby2.3 squiggly heredoc).

Usually, a test would show instantly if pull-requests would add that. So I think I go with testing on the oldest supported ruby, if I were to choose.

Please edit this PR as you wish, or close it. Thanks for your work and your involvement :)

**Comment by gonzalo-bulnes** [comment]
> The users would at least want to be able to choose ruby version without this gem dictating which version is required. And I think you are already there.

Yep. I don't think it makes sense for a tool like this one to impose any constraint on the ruby version. (Out of eventually asking for a supported one.) :+1: 

> This also means to restrain from using new constructs in code from recent rubies [... so] I think I go with testing on the oldest supported ruby, if I were to choose.

Sounds like a good choice to me. Additionally, nothing prevents us from targetting the latest current Ruby in the 2 series. I think two builds remains reasonable.


Rather than me editing it, do you want to `amend` your commit and push it again? (You'll have to `--force-with-lease` but I won't push to the branch and everything will be fine.)

**Comment by gonzalo-bulnes** [comment]
Thank you @jesperronn!

**Pull request merged**
