### PR TITLE
Allow single blueprint argument

### PR DESCRIPTION
**Pull request by rylnd**
@gonzalo-bulnes currently, one is unable to do the following:

```ruby
Dredd::Rack::RakeTask.new do |task|
  task.runner.configure do |dredd|
    dredd.paths_to_blueprints 'doc/*.apib'
  end
end
```

because the task exits early due to the # of arguments being checked _before_ we attempt to run the server (which has the side effect of adding an argument).

This is just a spike to get things working, so feel free to recommend a better solution. I tried my best to keep the documentation and tests up to date.

### CODE REVIEW

**Comment by rylnd** [comment]
@gonzalo-bulnes the above scenario silently fails in both 0.5.0 and 0.6.0. It raises an `InvalidCommandError` in 0.7.0.

**Comment by gonzalo-bulnes** [comment]
@rylnd,

I think I made a mistake and added the validation too early when running the command  (see the [code affected by the bug][affected], and the [code I think should not be affected by the bug][working]).

Would moving the command validation fix the issue?

```ruby
# lib/dredd/rack/runner.rb

# ...

# Run Dredd
#
# Returns true if the Dredd exit status is zero, false instead.
def run
  start_server! unless api_remote?
  raise InvalidCommandError.new(command) unless command_valid?
  Kernel.system(command)
end

# ...
```

If it does, that would be simpler than adding specific command-length validation, don't you think?

  [affected]: https://github.com/gonzalo-bulnes/dredd-rack/blob/master/lib/dredd/rack/runner.rb#L91-L98
  [working]: https://github.com/gonzalo-bulnes/dredd-rack/blob/v0.6.0/lib/dredd/rack/runner.rb#L91-L100

**Comment by gonzalo-bulnes** [comment]
@rylnd Ok, so **v0.6.0** is affected too, but fails silently. Performing the command validation after starting the server should solve both issues indeed, unless I'm wrong.

**Comment by rylnd** [comment]
@gonzalo-bulnes yes, I agree. I saw that solution, and somehow convinced myself that we didn't want to start the server unless the command is valid. If the only consequence of the fix is a slightly longer wait before an `InvalidCommandError` is raised, that works for me.

**Comment by gonzalo-bulnes** [comment]
@rylnd Thanks, I have to leave right now, but I'll think about it, maybe starting the server is not that bad, but maybe you were right and we should improve the command validation. Quick failure is always a good feature to have!

**Pull request closed without merging**
